### ISSUE TITLE
Server side module

### ISSUE THREAD

**Issue by ArtskydJ** [coding-in-the-wild/just-login-client#2]
Refactor `justlogin.xyz`'s dnode server code into this module. Then in `package.json` do:

``` json
{
  "index": "server.js",
  "browser": "client.js",
  ...
}
```

**Comment by TehShrike** [comment]
Huh, I hadn't realized that we'd tied dnode into this library.  That limits its use quite a bit, it seems.

**Comment by ArtskydJ** [comment]
Started this in 4a0f078102633087a56bbb96f0c6d6358f61256e.

Still needs tests!

**Comment by ArtskydJ** [comment]
Tests finished in https://github.com/coding-in-the-wild/just-login-client/commit/82aede76c1cbd7b8463a413984b3ab8724510a30.
