### ISSUE TITLE
Rename to justlogin.xyz-client

### ISSUE THREAD

**Issue by ArtskydJ** [coding-in-the-wild/just-login-client#3]
This is tied to `dnode`. It was built for justlogin.xyz.

It will probably be unhelpful to others using just-login.

**Comment by TehShrike** [comment]
Makes sense to me.

**Comment by ArtskydJ** [comment]
Makes sense to rename it? Or the way it is?

**Comment by TehShrike** [comment]
This issue makes sense to me - renaming it sounds like a good idea.

**Comment by ArtskydJ** [comment]
Fixed in https://github.com/coding-in-the-wild/justlogin.xyz-client/commit/4d13b03eab5bb15799a59027752736a8459482a9.
